jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_11_x:
        node_version: 11.x
      node_10_x:
        node_version: 10.x
      node_9_x:
        node_version: 9.x
      node_8_x:
        node_version: 8.x
      node_6_x:
        node_version: 6.x
    maxParallel: 5
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js
  - bash: alias npm="yarn"
    displayName: Use npm as alias for yarn
  - bash: npm -v
    displayName: Print yarn version
  - bash: yarn install --ignore-engines
    displayName: Install dependencies
  - bash: yarn lint
    displayName: Run linter
