// This file is autogenerated by build/build-validation.js, do not edit
/* istanbul ignore file */
"use strict";
module.exports = validate10;
module.exports.default = validate10;
const schema11 = {"type":"object","additionalProperties":false,"properties":{"connectionTimeout":{"type":"integer","default":0},"keepAliveTimeout":{"type":"integer","default":72000},"forceCloseConnections":{"type":"boolean","default":false},"maxRequestsPerSocket":{"type":"integer","default":0,"nullable":true},"requestTimeout":{"type":"integer","default":0},"bodyLimit":{"type":"integer","default":1048576},"caseSensitive":{"type":"boolean","default":true},"allowUnsafeRegex":{"type":"boolean","default":false},"http2":{"type":"boolean"},"https":{"if":{"not":{"oneOf":[{"type":"boolean"},{"type":"null"},{"type":"object","additionalProperties":false,"required":["allowHTTP1"],"properties":{"allowHTTP1":{"type":"boolean"}}}]}},"then":{"setDefaultValue":true}},"ignoreTrailingSlash":{"type":"boolean","default":false},"disableRequestLogging":{"type":"boolean","default":false},"jsonShorthand":{"type":"boolean","default":true},"maxParamLength":{"type":"integer","default":100},"onProtoPoisoning":{"type":"string","default":"error"},"onConstructorPoisoning":{"type":"string","default":"error"},"pluginTimeout":{"type":"integer","default":10000},"requestIdHeader":{"type":"string","default":"request-id"},"requestIdLogLabel":{"type":"string","default":"reqId"},"http2SessionTimeout":{"type":"integer","default":72000},"exposeHeadRoutes":{"type":"boolean","default":true},"versioning":{"type":"object","additionalProperties":true,"required":["storage","deriveVersion"],"properties":{"storage":{},"deriveVersion":{}}},"constraints":{"type":"object","additionalProperties":{"type":"object","required":["name","storage","validate","deriveConstraint"],"additionalProperties":true,"properties":{"name":{"type":"string"},"storage":{},"validate":{},"deriveConstraint":{}}}}}};
const func2 = Object.prototype.hasOwnProperty;

function validate10(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){
let vErrors = null;
let errors = 0;
if(errors === 0){
if(data && typeof data == "object" && !Array.isArray(data)){
if(data.connectionTimeout === undefined){
data.connectionTimeout = 0;
}
if(data.keepAliveTimeout === undefined){
data.keepAliveTimeout = 72000;
}
if(data.forceCloseConnections === undefined){
data.forceCloseConnections = false;
}
if(data.maxRequestsPerSocket === undefined){
data.maxRequestsPerSocket = 0;
}
if(data.requestTimeout === undefined){
data.requestTimeout = 0;
}
if(data.bodyLimit === undefined){
data.bodyLimit = 1048576;
}
if(data.caseSensitive === undefined){
data.caseSensitive = true;
}
if(data.allowUnsafeRegex === undefined){
data.allowUnsafeRegex = false;
}
if(data.ignoreTrailingSlash === undefined){
data.ignoreTrailingSlash = false;
}
if(data.disableRequestLogging === undefined){
data.disableRequestLogging = false;
}
if(data.jsonShorthand === undefined){
data.jsonShorthand = true;
}
if(data.maxParamLength === undefined){
data.maxParamLength = 100;
}
if(data.onProtoPoisoning === undefined){
data.onProtoPoisoning = "error";
}
if(data.onConstructorPoisoning === undefined){
data.onConstructorPoisoning = "error";
}
if(data.pluginTimeout === undefined){
data.pluginTimeout = 10000;
}
if(data.requestIdHeader === undefined){
data.requestIdHeader = "request-id";
}
if(data.requestIdLogLabel === undefined){
data.requestIdLogLabel = "reqId";
}
if(data.http2SessionTimeout === undefined){
data.http2SessionTimeout = 72000;
}
if(data.exposeHeadRoutes === undefined){
data.exposeHeadRoutes = true;
}
const _errs1 = errors;
for(const key0 in data){
if(!(func2.call(schema11.properties, key0))){
delete data[key0];
}
}
if(_errs1 === errors){
let data0 = data.connectionTimeout;
const _errs2 = errors;
if(!(((typeof data0 == "number") && (!(data0 % 1) && !isNaN(data0))) && (isFinite(data0)))){
let dataType0 = typeof data0;
let coerced0 = undefined;
if(!(coerced0 !== undefined)){
if(dataType0 === "boolean" || data0 === null
              || (dataType0 === "string" && data0 && data0 == +data0 && !(data0 % 1))){
coerced0 = +data0;
}
else {
validate10.errors = [{instancePath:instancePath+"/connectionTimeout",schemaPath:"#/properties/connectionTimeout/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced0 !== undefined){
data0 = coerced0;
if(data !== undefined){
data["connectionTimeout"] = coerced0;
}
}
}
var valid0 = _errs2 === errors;
if(valid0){
let data1 = data.keepAliveTimeout;
const _errs4 = errors;
if(!(((typeof data1 == "number") && (!(data1 % 1) && !isNaN(data1))) && (isFinite(data1)))){
let dataType1 = typeof data1;
let coerced1 = undefined;
if(!(coerced1 !== undefined)){
if(dataType1 === "boolean" || data1 === null
              || (dataType1 === "string" && data1 && data1 == +data1 && !(data1 % 1))){
coerced1 = +data1;
}
else {
validate10.errors = [{instancePath:instancePath+"/keepAliveTimeout",schemaPath:"#/properties/keepAliveTimeout/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced1 !== undefined){
data1 = coerced1;
if(data !== undefined){
data["keepAliveTimeout"] = coerced1;
}
}
}
var valid0 = _errs4 === errors;
if(valid0){
let data2 = data.forceCloseConnections;
const _errs6 = errors;
if(typeof data2 !== "boolean"){
let coerced2 = undefined;
if(!(coerced2 !== undefined)){
if(data2 === "false" || data2 === 0 || data2 === null){
coerced2 = false;
}
else if(data2 === "true" || data2 === 1){
coerced2 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/forceCloseConnections",schemaPath:"#/properties/forceCloseConnections/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced2 !== undefined){
data2 = coerced2;
if(data !== undefined){
data["forceCloseConnections"] = coerced2;
}
}
}
var valid0 = _errs6 === errors;
if(valid0){
let data3 = data.maxRequestsPerSocket;
const _errs8 = errors;
if((!(((typeof data3 == "number") && (!(data3 % 1) && !isNaN(data3))) && (isFinite(data3)))) && (data3 !== null)){
let dataType3 = typeof data3;
let coerced3 = undefined;
if(!(coerced3 !== undefined)){
if(dataType3 === "boolean" || data3 === null
              || (dataType3 === "string" && data3 && data3 == +data3 && !(data3 % 1))){
coerced3 = +data3;
}
else if(data3 === "" || data3 === 0 || data3 === false){
coerced3 = null;
}
else {
validate10.errors = [{instancePath:instancePath+"/maxRequestsPerSocket",schemaPath:"#/properties/maxRequestsPerSocket/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced3 !== undefined){
data3 = coerced3;
if(data !== undefined){
data["maxRequestsPerSocket"] = coerced3;
}
}
}
var valid0 = _errs8 === errors;
if(valid0){
let data4 = data.requestTimeout;
const _errs11 = errors;
if(!(((typeof data4 == "number") && (!(data4 % 1) && !isNaN(data4))) && (isFinite(data4)))){
let dataType4 = typeof data4;
let coerced4 = undefined;
if(!(coerced4 !== undefined)){
if(dataType4 === "boolean" || data4 === null
              || (dataType4 === "string" && data4 && data4 == +data4 && !(data4 % 1))){
coerced4 = +data4;
}
else {
validate10.errors = [{instancePath:instancePath+"/requestTimeout",schemaPath:"#/properties/requestTimeout/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced4 !== undefined){
data4 = coerced4;
if(data !== undefined){
data["requestTimeout"] = coerced4;
}
}
}
var valid0 = _errs11 === errors;
if(valid0){
let data5 = data.bodyLimit;
const _errs13 = errors;
if(!(((typeof data5 == "number") && (!(data5 % 1) && !isNaN(data5))) && (isFinite(data5)))){
let dataType5 = typeof data5;
let coerced5 = undefined;
if(!(coerced5 !== undefined)){
if(dataType5 === "boolean" || data5 === null
              || (dataType5 === "string" && data5 && data5 == +data5 && !(data5 % 1))){
coerced5 = +data5;
}
else {
validate10.errors = [{instancePath:instancePath+"/bodyLimit",schemaPath:"#/properties/bodyLimit/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced5 !== undefined){
data5 = coerced5;
if(data !== undefined){
data["bodyLimit"] = coerced5;
}
}
}
var valid0 = _errs13 === errors;
if(valid0){
let data6 = data.caseSensitive;
const _errs15 = errors;
if(typeof data6 !== "boolean"){
let coerced6 = undefined;
if(!(coerced6 !== undefined)){
if(data6 === "false" || data6 === 0 || data6 === null){
coerced6 = false;
}
else if(data6 === "true" || data6 === 1){
coerced6 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/caseSensitive",schemaPath:"#/properties/caseSensitive/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced6 !== undefined){
data6 = coerced6;
if(data !== undefined){
data["caseSensitive"] = coerced6;
}
}
}
var valid0 = _errs15 === errors;
if(valid0){
let data7 = data.allowUnsafeRegex;
const _errs17 = errors;
if(typeof data7 !== "boolean"){
let coerced7 = undefined;
if(!(coerced7 !== undefined)){
if(data7 === "false" || data7 === 0 || data7 === null){
coerced7 = false;
}
else if(data7 === "true" || data7 === 1){
coerced7 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/allowUnsafeRegex",schemaPath:"#/properties/allowUnsafeRegex/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced7 !== undefined){
data7 = coerced7;
if(data !== undefined){
data["allowUnsafeRegex"] = coerced7;
}
}
}
var valid0 = _errs17 === errors;
if(valid0){
if(data.http2 !== undefined){
let data8 = data.http2;
const _errs19 = errors;
if(typeof data8 !== "boolean"){
let coerced8 = undefined;
if(!(coerced8 !== undefined)){
if(data8 === "false" || data8 === 0 || data8 === null){
coerced8 = false;
}
else if(data8 === "true" || data8 === 1){
coerced8 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/http2",schemaPath:"#/properties/http2/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced8 !== undefined){
data8 = coerced8;
if(data !== undefined){
data["http2"] = coerced8;
}
}
}
var valid0 = _errs19 === errors;
}
else {
var valid0 = true;
}
if(valid0){
if(data.https !== undefined){
let data9 = data.https;
const _errs21 = errors;
const _errs22 = errors;
let valid1 = true;
const _errs23 = errors;
const _errs24 = errors;
const _errs25 = errors;
const _errs26 = errors;
let valid3 = false;
let passing0 = null;
const _errs27 = errors;
if(typeof data9 !== "boolean"){
let coerced9 = undefined;
if(!(coerced9 !== undefined)){
if(data9 === "false" || data9 === 0 || data9 === null){
coerced9 = false;
}
else if(data9 === "true" || data9 === 1){
coerced9 = true;
}
else {
const err0 = {};
if(vErrors === null){
vErrors = [err0];
}
else {
vErrors.push(err0);
}
errors++;
}
}
if(coerced9 !== undefined){
data9 = coerced9;
if(data !== undefined){
data["https"] = coerced9;
}
}
}
var _valid1 = _errs27 === errors;
if(_valid1){
valid3 = true;
passing0 = 0;
}
const _errs29 = errors;
if(data9 !== null){
let coerced10 = undefined;
if(!(coerced10 !== undefined)){
if(data9 === "" || data9 === 0 || data9 === false){
coerced10 = null;
}
else {
const err1 = {};
if(vErrors === null){
vErrors = [err1];
}
else {
vErrors.push(err1);
}
errors++;
}
}
if(coerced10 !== undefined){
data9 = coerced10;
if(data !== undefined){
data["https"] = coerced10;
}
}
}
var _valid1 = _errs29 === errors;
if(_valid1 && valid3){
valid3 = false;
passing0 = [passing0, 1];
}
else {
if(_valid1){
valid3 = true;
passing0 = 1;
}
const _errs31 = errors;
if(errors === _errs31){
if(data9 && typeof data9 == "object" && !Array.isArray(data9)){
let missing0;
if((data9.allowHTTP1 === undefined) && (missing0 = "allowHTTP1")){
const err2 = {};
if(vErrors === null){
vErrors = [err2];
}
else {
vErrors.push(err2);
}
errors++;
}
else {
const _errs33 = errors;
for(const key1 in data9){
if(!(key1 === "allowHTTP1")){
delete data9[key1];
}
}
if(_errs33 === errors){
if(data9.allowHTTP1 !== undefined){
let data10 = data9.allowHTTP1;
if(typeof data10 !== "boolean"){
let coerced11 = undefined;
if(!(coerced11 !== undefined)){
if(data10 === "false" || data10 === 0 || data10 === null){
coerced11 = false;
}
else if(data10 === "true" || data10 === 1){
coerced11 = true;
}
else {
const err3 = {};
if(vErrors === null){
vErrors = [err3];
}
else {
vErrors.push(err3);
}
errors++;
}
}
if(coerced11 !== undefined){
data10 = coerced11;
if(data9 !== undefined){
data9["allowHTTP1"] = coerced11;
}
}
}
}
}
}
}
else {
const err4 = {};
if(vErrors === null){
vErrors = [err4];
}
else {
vErrors.push(err4);
}
errors++;
}
}
var _valid1 = _errs31 === errors;
if(_valid1 && valid3){
valid3 = false;
passing0 = [passing0, 2];
}
else {
if(_valid1){
valid3 = true;
passing0 = 2;
}
}
}
if(!valid3){
const err5 = {};
if(vErrors === null){
vErrors = [err5];
}
else {
vErrors.push(err5);
}
errors++;
}
else {
errors = _errs26;
if(vErrors !== null){
if(_errs26){
vErrors.length = _errs26;
}
else {
vErrors = null;
}
}
}
var valid2 = _errs25 === errors;
if(valid2){
const err6 = {};
if(vErrors === null){
vErrors = [err6];
}
else {
vErrors.push(err6);
}
errors++;
}
else {
errors = _errs24;
if(vErrors !== null){
if(_errs24){
vErrors.length = _errs24;
}
else {
vErrors = null;
}
}
}
var _valid0 = _errs23 === errors;
errors = _errs22;
if(vErrors !== null){
if(_errs22){
vErrors.length = _errs22;
}
else {
vErrors = null;
}
}
if(_valid0){
const _errs36 = errors;
data["https"] = true;
var _valid0 = _errs36 === errors;
valid1 = _valid0;
}
if(!valid1){
const err7 = {instancePath:instancePath+"/https",schemaPath:"#/properties/https/if",keyword:"if",params:{failingKeyword: "then"},message:"must match \"then\" schema"};
if(vErrors === null){
vErrors = [err7];
}
else {
vErrors.push(err7);
}
errors++;
validate10.errors = vErrors;
return false;
}
var valid0 = _errs21 === errors;
}
else {
var valid0 = true;
}
if(valid0){
let data11 = data.ignoreTrailingSlash;
const _errs37 = errors;
if(typeof data11 !== "boolean"){
let coerced12 = undefined;
if(!(coerced12 !== undefined)){
if(data11 === "false" || data11 === 0 || data11 === null){
coerced12 = false;
}
else if(data11 === "true" || data11 === 1){
coerced12 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/ignoreTrailingSlash",schemaPath:"#/properties/ignoreTrailingSlash/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced12 !== undefined){
data11 = coerced12;
if(data !== undefined){
data["ignoreTrailingSlash"] = coerced12;
}
}
}
var valid0 = _errs37 === errors;
if(valid0){
let data12 = data.disableRequestLogging;
const _errs39 = errors;
if(typeof data12 !== "boolean"){
let coerced13 = undefined;
if(!(coerced13 !== undefined)){
if(data12 === "false" || data12 === 0 || data12 === null){
coerced13 = false;
}
else if(data12 === "true" || data12 === 1){
coerced13 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/disableRequestLogging",schemaPath:"#/properties/disableRequestLogging/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced13 !== undefined){
data12 = coerced13;
if(data !== undefined){
data["disableRequestLogging"] = coerced13;
}
}
}
var valid0 = _errs39 === errors;
if(valid0){
let data13 = data.jsonShorthand;
const _errs41 = errors;
if(typeof data13 !== "boolean"){
let coerced14 = undefined;
if(!(coerced14 !== undefined)){
if(data13 === "false" || data13 === 0 || data13 === null){
coerced14 = false;
}
else if(data13 === "true" || data13 === 1){
coerced14 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/jsonShorthand",schemaPath:"#/properties/jsonShorthand/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced14 !== undefined){
data13 = coerced14;
if(data !== undefined){
data["jsonShorthand"] = coerced14;
}
}
}
var valid0 = _errs41 === errors;
if(valid0){
let data14 = data.maxParamLength;
const _errs43 = errors;
if(!(((typeof data14 == "number") && (!(data14 % 1) && !isNaN(data14))) && (isFinite(data14)))){
let dataType15 = typeof data14;
let coerced15 = undefined;
if(!(coerced15 !== undefined)){
if(dataType15 === "boolean" || data14 === null
              || (dataType15 === "string" && data14 && data14 == +data14 && !(data14 % 1))){
coerced15 = +data14;
}
else {
validate10.errors = [{instancePath:instancePath+"/maxParamLength",schemaPath:"#/properties/maxParamLength/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced15 !== undefined){
data14 = coerced15;
if(data !== undefined){
data["maxParamLength"] = coerced15;
}
}
}
var valid0 = _errs43 === errors;
if(valid0){
let data15 = data.onProtoPoisoning;
const _errs45 = errors;
if(typeof data15 !== "string"){
let dataType16 = typeof data15;
let coerced16 = undefined;
if(!(coerced16 !== undefined)){
if(dataType16 == "number" || dataType16 == "boolean"){
coerced16 = "" + data15;
}
else if(data15 === null){
coerced16 = "";
}
else {
validate10.errors = [{instancePath:instancePath+"/onProtoPoisoning",schemaPath:"#/properties/onProtoPoisoning/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
if(coerced16 !== undefined){
data15 = coerced16;
if(data !== undefined){
data["onProtoPoisoning"] = coerced16;
}
}
}
var valid0 = _errs45 === errors;
if(valid0){
let data16 = data.onConstructorPoisoning;
const _errs47 = errors;
if(typeof data16 !== "string"){
let dataType17 = typeof data16;
let coerced17 = undefined;
if(!(coerced17 !== undefined)){
if(dataType17 == "number" || dataType17 == "boolean"){
coerced17 = "" + data16;
}
else if(data16 === null){
coerced17 = "";
}
else {
validate10.errors = [{instancePath:instancePath+"/onConstructorPoisoning",schemaPath:"#/properties/onConstructorPoisoning/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
if(coerced17 !== undefined){
data16 = coerced17;
if(data !== undefined){
data["onConstructorPoisoning"] = coerced17;
}
}
}
var valid0 = _errs47 === errors;
if(valid0){
let data17 = data.pluginTimeout;
const _errs49 = errors;
if(!(((typeof data17 == "number") && (!(data17 % 1) && !isNaN(data17))) && (isFinite(data17)))){
let dataType18 = typeof data17;
let coerced18 = undefined;
if(!(coerced18 !== undefined)){
if(dataType18 === "boolean" || data17 === null
              || (dataType18 === "string" && data17 && data17 == +data17 && !(data17 % 1))){
coerced18 = +data17;
}
else {
validate10.errors = [{instancePath:instancePath+"/pluginTimeout",schemaPath:"#/properties/pluginTimeout/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced18 !== undefined){
data17 = coerced18;
if(data !== undefined){
data["pluginTimeout"] = coerced18;
}
}
}
var valid0 = _errs49 === errors;
if(valid0){
let data18 = data.requestIdHeader;
const _errs51 = errors;
if(typeof data18 !== "string"){
let dataType19 = typeof data18;
let coerced19 = undefined;
if(!(coerced19 !== undefined)){
if(dataType19 == "number" || dataType19 == "boolean"){
coerced19 = "" + data18;
}
else if(data18 === null){
coerced19 = "";
}
else {
validate10.errors = [{instancePath:instancePath+"/requestIdHeader",schemaPath:"#/properties/requestIdHeader/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
if(coerced19 !== undefined){
data18 = coerced19;
if(data !== undefined){
data["requestIdHeader"] = coerced19;
}
}
}
var valid0 = _errs51 === errors;
if(valid0){
let data19 = data.requestIdLogLabel;
const _errs53 = errors;
if(typeof data19 !== "string"){
let dataType20 = typeof data19;
let coerced20 = undefined;
if(!(coerced20 !== undefined)){
if(dataType20 == "number" || dataType20 == "boolean"){
coerced20 = "" + data19;
}
else if(data19 === null){
coerced20 = "";
}
else {
validate10.errors = [{instancePath:instancePath+"/requestIdLogLabel",schemaPath:"#/properties/requestIdLogLabel/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
if(coerced20 !== undefined){
data19 = coerced20;
if(data !== undefined){
data["requestIdLogLabel"] = coerced20;
}
}
}
var valid0 = _errs53 === errors;
if(valid0){
let data20 = data.http2SessionTimeout;
const _errs55 = errors;
if(!(((typeof data20 == "number") && (!(data20 % 1) && !isNaN(data20))) && (isFinite(data20)))){
let dataType21 = typeof data20;
let coerced21 = undefined;
if(!(coerced21 !== undefined)){
if(dataType21 === "boolean" || data20 === null
              || (dataType21 === "string" && data20 && data20 == +data20 && !(data20 % 1))){
coerced21 = +data20;
}
else {
validate10.errors = [{instancePath:instancePath+"/http2SessionTimeout",schemaPath:"#/properties/http2SessionTimeout/type",keyword:"type",params:{type: "integer"},message:"must be integer"}];
return false;
}
}
if(coerced21 !== undefined){
data20 = coerced21;
if(data !== undefined){
data["http2SessionTimeout"] = coerced21;
}
}
}
var valid0 = _errs55 === errors;
if(valid0){
let data21 = data.exposeHeadRoutes;
const _errs57 = errors;
if(typeof data21 !== "boolean"){
let coerced22 = undefined;
if(!(coerced22 !== undefined)){
if(data21 === "false" || data21 === 0 || data21 === null){
coerced22 = false;
}
else if(data21 === "true" || data21 === 1){
coerced22 = true;
}
else {
validate10.errors = [{instancePath:instancePath+"/exposeHeadRoutes",schemaPath:"#/properties/exposeHeadRoutes/type",keyword:"type",params:{type: "boolean"},message:"must be boolean"}];
return false;
}
}
if(coerced22 !== undefined){
data21 = coerced22;
if(data !== undefined){
data["exposeHeadRoutes"] = coerced22;
}
}
}
var valid0 = _errs57 === errors;
if(valid0){
if(data.versioning !== undefined){
let data22 = data.versioning;
const _errs59 = errors;
if(errors === _errs59){
if(data22 && typeof data22 == "object" && !Array.isArray(data22)){
let missing1;
if(((data22.storage === undefined) && (missing1 = "storage")) || ((data22.deriveVersion === undefined) && (missing1 = "deriveVersion"))){
validate10.errors = [{instancePath:instancePath+"/versioning",schemaPath:"#/properties/versioning/required",keyword:"required",params:{missingProperty: missing1},message:"must have required property '"+missing1+"'"}];
return false;
}
}
else {
validate10.errors = [{instancePath:instancePath+"/versioning",schemaPath:"#/properties/versioning/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
var valid0 = _errs59 === errors;
}
else {
var valid0 = true;
}
if(valid0){
if(data.constraints !== undefined){
let data23 = data.constraints;
const _errs62 = errors;
if(errors === _errs62){
if(data23 && typeof data23 == "object" && !Array.isArray(data23)){
for(const key2 in data23){
let data24 = data23[key2];
const _errs65 = errors;
if(errors === _errs65){
if(data24 && typeof data24 == "object" && !Array.isArray(data24)){
let missing2;
if(((((data24.name === undefined) && (missing2 = "name")) || ((data24.storage === undefined) && (missing2 = "storage"))) || ((data24.validate === undefined) && (missing2 = "validate"))) || ((data24.deriveConstraint === undefined) && (missing2 = "deriveConstraint"))){
validate10.errors = [{instancePath:instancePath+"/constraints/" + key2.replace(/~/g, "~0").replace(/\//g, "~1"),schemaPath:"#/properties/constraints/additionalProperties/required",keyword:"required",params:{missingProperty: missing2},message:"must have required property '"+missing2+"'"}];
return false;
}
else {
if(data24.name !== undefined){
let data25 = data24.name;
if(typeof data25 !== "string"){
let dataType23 = typeof data25;
let coerced23 = undefined;
if(!(coerced23 !== undefined)){
if(dataType23 == "number" || dataType23 == "boolean"){
coerced23 = "" + data25;
}
else if(data25 === null){
coerced23 = "";
}
else {
validate10.errors = [{instancePath:instancePath+"/constraints/" + key2.replace(/~/g, "~0").replace(/\//g, "~1")+"/name",schemaPath:"#/properties/constraints/additionalProperties/properties/name/type",keyword:"type",params:{type: "string"},message:"must be string"}];
return false;
}
}
if(coerced23 !== undefined){
data25 = coerced23;
if(data24 !== undefined){
data24["name"] = coerced23;
}
}
}
}
}
}
else {
validate10.errors = [{instancePath:instancePath+"/constraints/" + key2.replace(/~/g, "~0").replace(/\//g, "~1"),schemaPath:"#/properties/constraints/additionalProperties/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
var valid5 = _errs65 === errors;
if(!valid5){
break;
}
}
}
else {
validate10.errors = [{instancePath:instancePath+"/constraints",schemaPath:"#/properties/constraints/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
var valid0 = _errs62 === errors;
}
else {
var valid0 = true;
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
else {
validate10.errors = [{instancePath,schemaPath:"#/type",keyword:"type",params:{type: "object"},message:"must be object"}];
return false;
}
}
validate10.errors = vErrors;
return errors === 0;
}


module.exports.defaultInitOptions = {"connectionTimeout":0,"keepAliveTimeout":72000,"forceCloseConnections":false,"maxRequestsPerSocket":0,"requestTimeout":0,"bodyLimit":1048576,"caseSensitive":true,"allowUnsafeRegex":false,"disableRequestLogging":false,"jsonShorthand":true,"ignoreTrailingSlash":false,"maxParamLength":100,"onProtoPoisoning":"error","onConstructorPoisoning":"error","pluginTimeout":10000,"requestIdHeader":"request-id","requestIdLogLabel":"reqId","http2SessionTimeout":72000,"exposeHeadRoutes":true}
