#!/bin/bash
./tools/replace_key.sh "[Symbol.for('fastify.children')]" "[symbols.childrenKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.bodyLimit')]" "[symbols.bodyLimitKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.routePrefix')]" "[symbols.routePrefixKey]"
./tools/replace_key.sh "[Symbol.for('fastify.logLevel')]" "[symbols.logLevelKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.contentTypeParser')]" "[symbols.contentTypeParserKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.Reply')]" "[symbols.ReplyKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.Request')]" "[symbols.RequestKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.hooks')]" "[symbols.hooksKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.schemas')]" "[symbols.schemasKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.middlewares')]" "[symbols.middlewaresKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.canSetNotFoundHandler')]" "[symbols.canSetNotFoundHandlerKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.404LevelInstance')]" "[symbols.404LevelInstanceKey]" 
./tools/replace_key.sh "[Symbol.for('fastify.404Context')]" "[symbols.404ContextKey]" 
