# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", group: :jekyll_plugins
gem "minima", "~> 2.0"

# If you have any plugins, put them here!
group :jekyll_plugins do

end
