# dependabot[bot]

name: Dependabot Auto Merge

on:
  check_suite:
    types:
      - completed
  pull_request:
    types:
      - edited
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  worker:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: ridedott/merge-me-action@v1.8.28
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{github.token}}
