name: integration NSolid

on:
  push:
    branches:
     - main
     - master
     - next
     - 'v*'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  install-production:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18, 20]
        pnpm-version: [8]
        include:
          - nsolid-version: 5
            node-version: 18
          - nsolid-version: 5
            node-version: 20
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: nodesource/setup-nsolid@v1
        with:
          node-version: ${{ matrix.node-version }}
          nsolid-version: ${{ matrix.nsolid-version }}

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      
      - name: Install Production
        run: |
          pnpm install --prod

      - name: Run server
        run: |
          node integration/server.js &

      - name: Test
        if: ${{ success() }}
        run: |
          bash integration/test.sh
