name: Lint Ecosystem Order

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/Ecosystem.md"

permissions:
  contents: read

jobs:
  build:
    name: Lint Ecosystem Order
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Lint Doc
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/lint-ecosystem.js')
            await script({ core })
