name: Test compare
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  run:
    if: contains(github.event.pull_request.labels.*.name, 'test-compare')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Test compare
        uses: nearform-actions/github-action-test-compare@v1
        with:
          label: test-compare
          testCommand: 'npm run test:ci'
