name: website

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  release:
    types:
      - released

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build website
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -H 'Circle-Token: ${{ secrets.circleci_token }}' \
            -d '{"branch":"master"}' \
            "https://circleci.com/api/v2/project/gh/fastify/website/pipeline"
