name: website

on:
  push:
    branches:
      - main
    paths:
      - 'docs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build website
        run: |
          curl -X POST --header 'Content-Type: application/json' "https://circleci.com/api/v1.1/project/github/fastify/website?circle-token=${{ secrets.circleci_token }}"
